### ISSUE TITLE
Merge AuthSucceededState and ContinuationState

### ISSUE THREAD

**Issue by icidasset** [fission-codes/webnative-elm#14]
Into one type alias, as they are the same.

**Comment by icidasset** [comment]
Not sure if we should merge the `State`s `Continuation` and `AuthSucceeded` entirely. Is there ever a case we need to distinguish between the two?

**Comment by matheus23** [comment]
I support this idea! We can totally just add another property `justSignedUp : Bool`.

If we make sure that the new type and the old type are isomorphic, then if we mess something up, in the worst case a user of the library will be able to shape the information in the way they want to. In other words: I'd say let's make it more convenient, but keep all information by making it isomorphic to the old type.
