### ISSUE TITLE
Update the Elm package repository with the github organization name change

### ISSUE THREAD

**Issue by darrow97** [fission-codes/webnative-elm#18]
# Summary

## Problem

My team and I came across this error when using the webnative-elm package post github organization change and were met with this error: 
`
[vite-plugin-elm] Compilation failed
Starting downloads...

  ✗ fission-suite/webnative-elm 7.0.0

Verifying dependencies (21/21)-- CORRUPT PACKAGE DATA --------------------------------------------------------

I downloaded the source code for fission-suite/webnative-elm 7.0.0 from:

    https://github.com/fission-suite/webnative-elm/zipball/7.0.0/

But it looks like the hash of the archive has changed since publication:

  Expected: b94ec7b47fc0d13fec240cf307114339b39475cc
    Actual: f73a20b5c5ed208088a3a4db4b85aee878fcaa96

This usually means that the package author moved the version tag, so report it
to them and see if that is the issue. Folks on Elm slack can probably help as
well.

Dependency problem!
`
The checksum comparison for `https://github.com/fission-suite/webnative-elm/zipball/7.0.0/` fails because the Elm package manager is still looking for `fission-suite/webnative-elm`.

### Impact

Project compilation fails because of this and prevents further development.

## Solution

Update the Elm package repository.

# Detail

**Describe the bug**
See section Problem.

**To Reproduce**
1. Add webnative-elm as a dependency for an elm project
2. Build project (we use Vite for building projects)

**Expected behavior**
Ideally, a clean build. More accurately, this error is not the cause of a failed build.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Brave (N/A?)

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by bmann** [comment]
Thanks @darrow97 -- @icidasset @matheus23 can one of you please update this.

**Comment by matheus23** [comment]
Sorry about that! Github tarball hashes break when the organization is renamed. We recently renamed from `fission-suite` to `fission-codes` to match our website.

I've now uploaded `fission-codes/webnative-elm`. It starts at version 1.0.0 again, please use that. Unfortunately there's no way to fix or remove the old version as far as I know.

**Comment by icidasset** [comment]
@matheus23 I guess there's also no way to bump the new elm package version up to 7.x so that it's in sync with the NPM package? If only elm packages had a deprecation flag/warning.

**Comment by matheus23** [comment]
Yep, as far as I could figure it out, there's no way.
